Update rtgetscripts

diff --git a/rtgetscripts b/rtgetscripts
--- a/rtgetscripts
+++ b/rtgetscripts
@@ -12,22 +12,20 @@ while [ $script_size = 0 ]
   do
     rm -f $script_name
     attempts=$(( $attempts + 1 ))
-    if [ $attempts = 20 ]
-      then
-        echo "There is a problem downloading the scripts. Please check your network or there may be an issue with the github website"
-        echo "If the Github website is down, you can try again later"
-        exit 1
+    if [ $attempts = 20 ]; then
+      echo "There is a problem downloading the scripts. Please check your network or there may be an issue with the github website"
+      echo "If the Github website is down, you can try again later"
+      exit 1
     fi
     wget --no-check-certificate https://raw.githubusercontent.com/arakasi72/rtinst/master/$script_name
     script_size=$(du -b $script_name | cut -f1)
   done
 
-if ! [ -z "$script_dest" ]
-  then
-    mv -f $script_name $script_dest
-    if case $script_dest in *"${bindest}"*) true;; *) false;; esac; then
-      chmod 755 $script_dest
-    fi
+if ! [ -z "$script_dest" ]; then
+  mv -f $script_name $script_dest
+  if case $script_dest in *"${bindest}"*) true;; *) false;; esac; then
+    chmod 755 $script_dest
+  fi
 fi
 }
 
