Update rtadduser

diff --git a/scripts/rtadduser b/scripts/rtadduser
--- a/scripts/rtadduser
+++ b/scripts/rtadduser
@@ -238,9 +238,6 @@ fi
 
 echo "User name is $user"
 
-###REMOVE
-exit
-
 if id -u $user >/dev/null 2>&1; then
   echo "$user already exists"
 else
@@ -249,6 +246,13 @@ else
   else
     adduser --gecos "" $user --disabled-password
     echo "$user:$unixpass" | sudo chpasswd
+  fi
+
+  if id -u $user >/dev/null 2>&1; then
+    echo "$user successfully created"
+  else
+    echo "create user failed - exiting process"
+    exit 1
   fi
 fi
 
