Update rtinst

diff --git a/scripts/rtinst b/scripts/rtinst
--- a/scripts/rtinst
+++ b/scripts/rtinst
@@ -96,6 +96,21 @@ tr -dc A-Za-z0-9 < /dev/urandom | head -c ${genln} | xargs
 early_exit() {
 echo "Installation is incomplete. Run rtinst again to complete"
 echo
+if hash rtorrent >> /dev/null 2>&1; then
+  rtorrent_current=$(rtorrent -h | grep -m 1 'version')
+  rtorrent_current=${rtorrent_current#*version }
+  echo "rtorrent $rtorrent_current installed"
+else
+  echo "rtorrent was not installed"
+fi
+echo
+ru_installed=$(grep -m 1 version: /var/www/rutorrent/js/webui.js | cut -d \" -f2)
+if [ -z $ru_installed ]; then
+  echo "RuTorrent was not installed"
+else
+  echo "RuTorrent $ru_installed installed
+fi
+echo
 echo "FTP Port set to $ftpport"
 echo
 echo "IMPORTANT - SSH Port has been set to: $sshport"
@@ -646,6 +661,8 @@ sed -i "s/<user name>/$user/g" $home/.rtorrent.rc
 
 mkdir -p /var/www
 cd /var/www
+
+echo -n "RuTorrent: "; check_url $ru_url && echo "OK" || { echo "FAIL"; early_exit; }
 
 if [ -d "/var/www/rutorrent" ]; then
   rm -r /var/www/rutorrent
