Update rtupdate

diff --git a/scripts/rtupdate b/scripts/rtupdate
--- a/scripts/rtupdate
+++ b/scripts/rtupdate
@@ -14,11 +14,11 @@ osname=$(lsb_release -si)
 relno=$(lsb_release -sr | cut -d. -f1)
 sourcedir='http://rtorrent.net/downloads/'
 
-xmlrpc_url='https://svn.code.sf.net/p/xmlrpc-c/code/stable/'
-xmlrpcloc='https://svn.code.sf.net/p/xmlrpc-c/code/stable/'
+#xmlrpc_url='https://svn.code.sf.net/p/xmlrpc-c/code/stable/'
+#xmlrpcloc='https://svn.code.sf.net/p/xmlrpc-c/code/stable/'
 
-xmlrpc_url_alt='https://github.com/mirror/xmlrpc-c'
-xmlrpcloc_alt='https://github.com/mirror/xmlrpc-c/trunk/stable'
+xmlrpc_url='https://github.com/mirror/xmlrpc-c'
+xmlrpcloc='https://github.com/mirror/xmlrpc-c/trunk/stable'
 
 rtdevrel=1
 
@@ -98,19 +98,7 @@ rt_repo=0
 echo
 echo "Checking File Repositories"
 
-echo -n "xmlrpc-c: "
-if check_url $xmlrpc_url; then
-  echo "OK"
-else
-  xmlrpc_url=$xmlroc_url_alt
-  xmlrpcloc=$xmlrpcloc_alt
-  if check_url $xmlrpc_url ; then
-    echo "OK"
-  else
-    echo "FAIL"
-    xmlrpc_repo=1
-  fi
-fi
+echo -n "xmlrpc-c: "; check_url $xmlrpc_url && echo "OK" || { echo "FAIL"; xmlrpc_repo=1; }
 
 echo -n "rtorrent: "; check_url $sourcedir && echo "OK" || { echo "FAIL"; rt_repo=1; }
 
