Update rtupdate

diff --git a/scripts/rtupdate b/scripts/rtupdate
--- a/scripts/rtupdate
+++ b/scripts/rtupdate
@@ -92,7 +92,7 @@ xmlrpc_repo=0
 rt_repo=0
 echo
 echo "Checking File Repositories"
-echo -n "xmlrpc-c: "; check_url $xmlrpcloc && echo "OK" || { echo "FAIL"; xmlrpc_repo=1; }
+#echo -n "xmlrpc-c: "; check_url $xmlrpcloc && echo "OK" || { echo "FAIL"; xmlrpc_repo=1; }
 echo -n "rtorrent: "; check_url $sourcedir && echo "OK" || { echo "FAIL"; rt_repo=1; }
 
 if [ $rt_repo = 1 ]; then
