Update rtupdate

diff --git a/scripts/rtupdate b/scripts/rtupdate
--- a/scripts/rtupdate
+++ b/scripts/rtupdate
@@ -97,7 +97,7 @@ xmlrpc_repo=0
 rt_repo=0
 echo
 echo "Checking File Repositories"
-echo -n "xmlrpc-c: "; check_url $xmlrpc_url && echo "OK" || xmlrpc_url=$xmlroc_url_alt ; xmlrpcloc=$xmlrpcloc_alt; check_url $xmlrpc_url && echo "OK" || { echo "FAIL"; xmlrpc_repo=1; }
+echo -n "xmlrpc-c: "; check_url $xmlrpc_url && echo "OK" || { xmlrpc_url=$xmlroc_url_alt ; xmlrpcloc=$xmlrpcloc_alt; check_url $xmlrpc_url } && echo "OK" || { echo "FAIL"; xmlrpc_repo=1; }
 echo -n "rtorrent: "; check_url $sourcedir && echo "OK" || { echo "FAIL"; rt_repo=1; }
 
 if [ $rt_repo = 1 ]; then
